name: Node CI

on: [push]

jobs:
  build_on_linux:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Use Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.16
    - name: npm install
      run: npm install
    - name: npm test
      run: npm test
      env:
        GOPATH: /home/runner/work/socketsupply/fake-api-gateway-lambda
  build_on_windows:
    runs-on: windows-2022
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Use Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.16
    - name: setup go env stuff
      run: |
        echo "::set-env name=GOPATH::$(go env GOPATH)"
        echo "::add-path::$(go env GOPATH)/bin"
      shell: bash
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    - name: npm install
      run: npm install
    - name: npm test
      run: npm test
